### ISSUE TITLE
temporary solution to hosting build artifacts for CLI

### ISSUE THREAD

**Issue by kleinschmidt** [beacon-biosignals/Ray.jl#105]
Until we upstream our forked backend changes to the ray project, we need some way to host build artifacts so our internal users can install teh CLI without requiring the whole build toolchain.  A few possibilities:

- use a custom PyPI server
- store wheels (?) as github release assets
- store wheels in git LFS in a separate repo

**Comment by omus** [comment]
We've opted to store wheels as GitHub release assets in our fork. See https://github.com/beacon-biosignals/ray/releases/tag/ray-2.5.1%2B1 for an example
