### ISSUE TITLE
Initial release package structure

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/Ray.jl#124]
In #91 we discuss splitting up this repo into multiple repos to mirror the structure that most Julia packages and their related JLLs have. This separation normally exists to isolate the JLL repos with automated commits from human commits. There are some downsides with this approach however including sometimes having to make changes across multiple repos and PRs.

In the case of Ray.jl it has been very useful to have the ray_julia_jll package inside the same repo to avoid having the "split-PR" issue. However, now that we are talking about making releases we need to tackle the issue of where to host the platform specific libraries needed by this package.

We already know that the initial plan is to build the platform specific shared libraries on their respective host platforms and not worry about cross compilation at this time (Bazel has been problematic to work with in the BinaryBuilder cross compilation environment). We may eventually use GitHub actions to make these build tarballs but we'll start with a more manual process as we need to setup a macOS M1 runner for this to be feasible. This means after the platform specific build completes we need some place to host the binaries. I propose the following procedure:

1. Create a tag (e.g. `v0.1.0`) against the a commit (doesn't have to be a commit on the `origin/HEAD`).
2. Create a draft pre-release GitHub release against the tag.
3. Build the tarballs on each supported platform and have these machines upload the tarball to the draft pre-release GitHub release.
4. Once all platforms have uploaded their tarballs the GitHub release is published (still a pre-release). By publishing the release the assets will be accessible from consistent URLs.
5. A PR is created which updates the Artifacts.toml with the GitHub release asset URLs. The CI workflows for this PR can run successfully and the referenced artifacts will be accessible.
6. Once the PR is merged the tag is updated to the merged commit and the GitHub release is updated to point to the updated tag.
7. The package can be registered normally now.

With this setup we are avoiding having bots generate commits against our repo (although some of the code may be generated). Because of this there really isn't much of a need for us to excise the ray_julia_jll into a separate repo.

Ideally, we should convert this package into a submodule of Ray.jl as this would not require us to even register this package separately and allow us to avoid split-PRs entirely. For example the Arrow and ArrowTypes packages currently both co-exist in the single repo of Arrow.jl. If a change to Arrow also required a change to ArrowTypes you could make that change in a single PR but the CI workflows would fail as Arrow depends on the _released_ version of ArrowTypes. In the case of the Arrow/ArrowTypes these packages are required to be separate packages as it allows other packages to support Arrow tables by just depending on ArrowTypes and not the more heavy-weight Arrow package. However, in the case of Ray.jl I do not anticipate that anyone needs to use ray_julia_jll.jl independently from Ray.jl so a submodule should work just fine for us.

We may want to use a different name for the submodule and possibly drop depending on JLLWrappers but those decisions can come later.

**Comment by omus** [comment]
General notes around using GitHub releases with mutable tags:

- Draft GitHub releases host assets at `https://github.com/beacon-biosignals/Ray.jl/releases/download/untagged-<random-hexidecimal>/<filename>` whether they are associated with a tag or not.
- Published pre-release and non-pre-release GitHub releases use the same URL for hosting assets: `https://github.com/beacon-biosignals/Ray.jl/releases/download/<tag>/<filename>`
- GitHub releases and their assets persist even with their associated tag is deleted. A published release is converted into a draft and the asset URL is changed.
- GitHub releases can be updated to be associated with an updated tag or a different tag

**Comment by glennmoy** [comment]
I think we can consolidate this into 3 broader stages of work:

* (1-3) Run `make.jl` on each platform/version create the initial tag+release and to generate+upload the assets 
* (4?-5) Run `artifacts.jl` once to un-draft the release, update the Artifacts.toml and push commits to branch. (Would be nice if we could programattically un-draft the release from the script to save a manual step)
* (6-7) Tag-switcheroo and register
