### ISSUE TITLE
Add tests for having multiple tasks in flight

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/Ray.jl#50]
> making these concurrent was intentional, that way we at least stress the path where there are >1 task in flight. not the biggest deal though adn we shoudl probably be testing that separately/explicitly.
– https://github.com/beacon-biosignals/ray_core_worker_julia_jll.jl/pull/47#discussion_r1307795836

**Comment by kleinschmidt** [comment]
this is done to my satisfaction with some of the tests from #126
