### ISSUE TITLE
Do not use sizeof in construcing LocalMemoryBuffer

### ISSUE THREAD

**Issue by glennmoy** [beacon-biosignals/Ray.jl#55]
Using `sizeof` is probably wrong for `pointer_from_objref` as there is probably
additional Julia type metadata not being accounted for. This may be why we see a
segfault when trying to use `pointer_from_objref`.

**Comment by omus** [comment]
This issus is referring to this testset: https://github.com/beacon-biosignals/Ray.jl/blob/fc586a252ff4d0312b5731ce3cd43c48db8c94ab/test/ray_julia_jll/buffer.jl#L21-L35

The comment isn't actually something to fix but is just a note about why copying data from a `pointer_from_objref` doesn't work. I'll revise the comments to be clearer and close this.
