### ISSUE TITLE
Avoid using `RAY_CHECK*`

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/Ray.jl#84]
> We shouldn't be using `RAY_CHECK*` because when it fails, it exits the process.  better to check + throw.  but we can handle that in a cleanup later.

_Originally posted by @kleinschmidt in https://github.com/beacon-biosignals/ray_core_worker_julia_jll.jl/pull/83#discussion_r1317280854_

**Comment by kleinschmidt** [comment]
THe core worker handles return _values_ for things like get/put by passing pointers for the outputs, and then returns the status.  this isn't a very julian idiom; we could support it by passing a `Ref` for the actual return value and then returning the status, but that feels pretty clunky.  This is all basically glue code anyway so we may be able to return something slightly awkward like a status/value tuple, or use a wrapper type to encapsulate.
