### ISSUE TITLE
Update async tests to ignore order

### ISSUE THREAD

**Issue by omus** [beacon-biosignals/Ray.jl#92]
Had the Julia 1.9 tests fail with:
```
Async waiting on task: Test Failed at /home/runner/work/ray_core_worker_julia_jll.jl/ray_core_worker_julia_jll.jl/test/task.jl:195
  Expression: results == [1, 10]
   Evaluated: Any[10, 1] == [1, 10]

Stacktrace:
 [1] macro expansion
   @ /opt/hostedtoolcache/julia/1.9.3/x64/share/julia/stdlib/v1.9/Test/src/Test.jl:478 [inlined]
 [2] macro expansion
   @ ~/work/ray_core_worker_julia_jll.jl/ray_core_worker_julia_jll.jl/test/task.jl:195 [inlined]
 [3] macro expansion
   @ /opt/hostedtoolcache/julia/1.9.3/x64/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
 [4] top-level scope
   @ ~/work/ray_core_worker_julia_jll.jl/ray_core_worker_julia_jll.jl/test/task.jl:187
```
– https://github.com/beacon-biosignals/ray_core_worker_julia_jll.jl/actions/runs/6102536017/job/16561202496?pr=90
 
~Looks like something to look into later~. The async nature of the test means that the order isn't deterministic

_Originally posted by @omus in https://github.com/beacon-biosignals/Ray.jl/issues/90#issuecomment-1709150388_

**Comment by kleinschmidt** [comment]
The order is actually _meant_ to be deterministic here to make sure we're really not blocking globally on a `get`.  I hoped that 10s vs. 1s woudl be a big enough delta to be reliable but I guess not :-/

**Comment by kleinschmidt** [comment]
I think a better way to test this would be to do one ray task that sleeps and another non-ray task that returns immediately.  But that could still in theory be non-deterministic...
